apiVersion: build.OpenShift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: qod-web # your application name
  name: qod-web # your application name
spec:
  output:
    to:
      kind: DockerImage
      name: quay.io/arief_amarullah/qod-ui:latest # add yourimage
  source:
    # Expect a local directory to be streamed to OpenShift as a build source
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      # Find the image build instructions in./Dockerfile
      dockerfilePath: Dockerfile
